version: '3.9'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "8081:8080"
    volumes:
      - ./client:/app
    depends_on:
      - server

  micro_db:
    image: postgres:15.3-alpine3.18
    container_name: micro_db
    environment:
      # POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - micro_db_data1:/data/postgres
      - micro_db_data2:/var/lib/postgresql/data
    ports:
      - "5432:5432"


networks:
  default:
    external: true
    name: nobin

volumes:
  micro_db_data1:
  micro_db_data2:

